06 implement file storage
Serg3/06_file_storage pull request #1
Opened 2021-06-11 08:07 UTC by Serg3

Part 6: Ввод-вывод (Input-output)

2021-06-14 10:04 UTC, DmitriyVTitov requested changes
Много нелогичностей. + Почитайте про Open-Close Principle

2021-06-14 10:04 UTC, DmitriyVTitov commented on cmd/srch/srch.go
> +	}
не
```
if *param == "" {Print...}
...
удачный путь без отступов и else!
```

2021-06-14 10:04 UTC, DmitriyVTitov commented on cmd/srch/srch.go
> +func scan() *index.Storage {
почему функция scan() возвращает хранилище? где логика?
и почему она без аргументов? откуда они берутся?

2021-06-14 10:04 UTC, DmitriyVTitov commented on cmd/srch/srch.go
> +		docs := scan().Search(param)
опять этот вызов scan().Search() - что это может означать?
Go -  не функциональный язык

2021-06-14 10:04 UTC, DmitriyVTitov commented on pkg/index/index.go
> +		fmt.Printf("Storage file was not found! Scanning started...\n\n")
зачем эта надпись здесь?
вы уверены, что мне, как пользователю пакета, она нужна?
ошибку надо возвращать, а я сам решу, что с ней делать

2021-06-14 19:42 UTC, DmitriyVTitov approved these changes
На мой взгляд, всё равно есть некоторые нелогичности, но в целом - ОК.

2021-06-14 19:42 UTC, DmitriyVTitov commented on pkg/storage/file.go
> +}
Типичное нарушение принципа OCP. Жёстко закодирован файл  и я захочу изменить код пакета, поскольку у меня другой файл с данными.
Пакет должен быть открыт для расширения, а не модификации. То есть инструменты пакета должны быть гибкими. Значит, функция Load() должна принимать io.Reader и загружать данные.

2021-06-15 09:39 UTC, Serg3 commented on pkg/storage/file.go
> +}
Логично, согласен. Оставлю сейчас так, как есть, приняв к сведению - времени остается маловато. Возможно где-то в дальнейшем еще придется это исправить.

2021-06-15 21:25 UTC, merged